### ISSUE TITLE
Definição da lista de requisitos

### ISSUE THREAD

**Issue by leandrolitano** [ventzz/cafe-filosofico#1]
- Cadastro de alunos
- Consulta de alunos
- Editação de alunos
- Remoção de alunos
- Cadastro de convidados
- Consulta de convidados
- Editação de convidados
- Remoção de convidados
- Autenticação de acesso
- Painel Administrativo
- Confirmação do Convidado

**Comment by ventzz** [comment]
Requisitos adicionados ao README.
